export {Navbar} from "./Navbar/Navbar"
export {HotelCard} from "./HotelCard/HotelCard"
export {Categories} from "./categories/categories"
export {HotelImages} from "./HotelImages/HotelImages" 
export {HotelDetails} from "./HotelDetails/HotelDetails"